In [2]:
# NDArray
# http://mxnet.io/tutorials/python/ndarray.html

In [3]:
import sys
sys.path.append('/usr/local/lib/python2.7/site-packages/mxnet-0.9.3-py2.7-macosx-10.12-x86_64.egg')


In [4]:
import mxnet as mx
import numpy as np

In [5]:
# Create a single-dimension array
a = mx.nd.array([1,2,3])
a.shape

(3L,)

In [6]:
# Create a multi-dimensional array
b = mx.nd.array([[1,2,3],[2,3,4]])
b.shape

(2L, 3L)

In [7]:
{'a.shape':a.shape, 'b.shape':b.shape}

{'a.shape': (3L,), 'b.shape': (2L, 3L)}

In [8]:
# Specify the element type with `dtype` using Numpy's datatypes
a = mx.nd.array([1,2,3]) # float32 is used by default

In [9]:
b = mx.nd.array([1,2,3], dtype = np.int32) # specify as int32

In [10]:
a.shape

(3L,)

In [11]:
c = mx.nd.array([1.2, 2.3, 3.4], dtype = np.float16) # specify as float16

In [12]:
c.shape

(3L,)

In [13]:
(a.dtype, b.dtype, c.dtype)

(numpy.float32, numpy.int32, numpy.float16)

In [14]:
# Initialize arrays without knowing values:

In [15]:
a = mx.nd.zeros((2,3))   # Init with all zeros
b = mx.nd.ones((2,3))    # Init with all ones
c = mx.nd.full((2,3), 7) # Init with all sevens

In [16]:
d = mx.nd.ones((2,3), dtype = np.int32)

In [17]:
d.asnumpy()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [18]:
# Basic Operations

In [19]:
e = mx.nd.array([[3,4,5],[5,6,7]])

In [20]:
c = a + e
c.asnumpy()

array([[ 3.,  4.,  5.],
       [ 5.,  6.,  7.]], dtype=float32)

In [21]:
(b + e).asnumpy()

array([[ 4.,  5.,  6.],
       [ 6.,  7.,  8.]], dtype=float32)

In [22]:
# Multiplication and Dot Product

In [23]:
a = mx.nd.ones((2,3))

In [24]:
a.shape

(2L, 3L)

In [25]:
b = mx.nd.ones(a.shape)

In [26]:
c = a * b

In [27]:
c.asnumpy()

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [28]:
b += a
b.asnumpy()

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.]], dtype=float32)

In [29]:
# Indexing and Slicing

In [31]:
print(np.arange(6).reshape(3,2))

[[0 1]
 [2 3]
 [4 5]]


In [32]:
a = mx.nd.array(np.arange(6).reshape(3,2))

In [33]:
a

<NDArray 3x2 @cpu(0)>

In [34]:
a[1:2]

<NDArray 1x2 @cpu(0)>

In [35]:
a = mx.nd.array(np.arange(6).reshape(3,2))

In [36]:
a

<NDArray 3x2 @cpu(0)>

In [37]:
a[:1]

<NDArray 1x2 @cpu(0)>

In [38]:
a[1:2] = 9

In [39]:
a[:].asnumpy()

array([[ 0.,  1.],
       [ 9.,  9.],
       [ 4.,  5.]], dtype=float32)